version: "3"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    container_name: webapp-task5
    networks:
      static-network:
        ipv4_address: 172.19.0.2

  redis:
    image: "redis:alpine"
    container_name: redis-task5
    networks:
      static-network:
        ipv4_address: 172.19.0.3

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.19.0.0/24
